---
- name: install base packages for spark
  apt: name={{ item }} state=present
  with_items:
    - openjdk-7-jdk

- name: ensure spark is installed
  copy: src=spark-1.4.1-bin-hadoop2.4.tgz dest=/opt/spark.tgz
