---
- name: restart zookeeper
  service: name=zookeeper state=restarted

- name: restart mesos services
  service: name={{ item }} state=restarted
  with_items:
    - mesos-master
    - marathon
    - chronos
